spring.application.name=smart-document-backend

server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/smart_document_db
spring.datasource.username=postgres
spring.datasource.password=123

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SQL initialization
spring.sql.init.mode=never
# Temporarily disable Redis Vector Store auto-configuration
spring.autoconfigure.exclude=org.springframework.ai.vectorstore.redis.autoconfigure.RedisVectorStoreAutoConfiguration
management.health.redis.enabled=false
logging.level.org.springframework.security=DEBUG